<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>9.0.30729</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{CAC7E4D1-71A4-4C05-BAC1-34201C067CF9}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>RebarPosCommands</RootNamespace>
    <AssemblyName>RebarPos</AssemblyName>
    <TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <OldToolsVersion>3.5</OldToolsVersion>
    <UpgradeBackupLocation />
    <TargetFrameworkProfile />
    <TargetFrameworkSubset>
    </TargetFrameworkSubset>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <FileAlignment>4096</FileAlignment>
    <BaseAddress>285212672</BaseAddress>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcDbMgd, Version=18.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\inc-x64\AcDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMgd, Version=18.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\inc-x64\AcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Commands_NewPos.cs" />
    <Compile Include="Commands.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Commands.resx</DependentUpon>
    </Compile>
    <Compile Include="Commands_PosEdit.cs" />
    <Compile Include="Commands_EmptyBalloons.cs" />
    <Compile Include="Commands_PosGroup.cs" />
    <Compile Include="DWGUtility.cs" />
    <Compile Include="Commands.cs" />
    <Compile Include="EditPosForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="EditPosForm.Designer.cs">
      <DependentUpon>EditPosForm.cs</DependentUpon>
    </Compile>
    <Compile Include="GroupForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="GroupForm.Designer.cs">
      <DependentUpon>GroupForm.cs</DependentUpon>
    </Compile>
    <Compile Include="PosShapeView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="PosShapeView.Designer.cs">
      <DependentUpon>PosShapeView.cs</DependentUpon>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="SelectShapeForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="SelectShapeForm.Designer.cs">
      <DependentUpon>SelectShapeForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Commands.resx">
      <DependentUpon>Commands.cs</DependentUpon>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Commands.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="EditPosForm.resx">
      <DependentUpon>EditPosForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="GroupForm.resx">
      <DependentUpon>GroupForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="PosShapeView.resx">
      <DependentUpon>PosShapeView.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="SelectShapeForm.resx">
      <DependentUpon>SelectShapeForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\arrow_left.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\cursor.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\textfield.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ManagedRebarPos\ManagedRebarPos.vcproj">
      <Project>{D26DC853-A22B-4C5B-810F-F76D1247FA93}</Project>
      <Name>ManagedRebarPos</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\dimension.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\add.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\delete.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\tick.png" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>